# Generated by Django 5.0.6 on 2024-05-20 08:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_ordermodel_paid_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name_on_card', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=200, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('exp_month', models.CharField(blank=True, max_length=2, null=True, validators=[django.core.validators.RegexValidator('^\\d{0,9}$')])),
                ('exp_year', models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator('^\\d{0,9}$')])),
                ('card_id', models.TextField(blank=True, max_length=100, null=True)),
                ('address_city', models.CharField(blank=True, max_length=120, null=True)),
                ('address_country', models.CharField(blank=True, max_length=120, null=True)),
                ('address_state', models.CharField(blank=True, max_length=120, null=True)),
                ('address_zip', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('^\\d{0,9}$')])),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='StripeModel',
        ),
    ]
